"""Add nullable destination_id to activities

Revision ID: e45957c4591e
Revises: 
Create Date: 2026-02-05 16:44:37.488394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45957c4591e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activitys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('activitys_name_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('activitys_type_key'), type_='unique')
        batch_op.create_foreign_key(None, 'destinations', ['destination_id'], ['id'])

    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('destinations_country_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('destinations_country_key'), ['country'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('activitys', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('activitys_type_key'), ['type'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('activitys_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('destination_id')

    # ### end Alembic commands ###
